// Generated by CoffeeScript 1.6.3
(function() {
  var LifeUI, global;

  LifeUI = {
    board: {},
    world: new World,
    buildBoard: function(id) {
      var col, div, elem, row, x, y, _i, _results;
      elem = document.getElementById(id);
      _results = [];
      for (y = _i = 50; _i >= -50; y = _i += -1) {
        row = document.createElement('tr');
        elem.appendChild(row);
        _results.push((function() {
          var _j, _results1;
          _results1 = [];
          for (x = _j = -50; _j <= 50; x = _j += 1) {
            col = document.createElement('td');
            row.appendChild(col);
            div = document.createElement('div');
            col.appendChild(div);
            _results1.push(this.board[new Point(x, y)] = div);
          }
          return _results1;
        }).call(this));
      }
      return _results;
    },
    buildWorld: function(coords) {
      var _this = this;
      return coords.forEach(function(coords) {
        return _this.world.add(new Point(coords[0], coords[1]));
      });
    },
    showPop: function() {
      var _this = this;
      return this.world.pop.each(function(p) {
        var div;
        div = _this.board[p];
        if (div) {
          return div.setAttribute('class', 'alive');
        }
      });
    },
    hidePop: function() {
      var _this = this;
      return this.world.pop.each(function(p) {
        var div;
        div = _this.board[p];
        if (div) {
          return div.removeAttribute('class');
        }
      });
    },
    loopForever: function() {
      var _this = this;
      this.showPop();
      return setTimeout(function() {
        _this.hidePop();
        _this.world.advance();
        return _this.loopForever();
      }, 200);
    },
    start: function(id, coords) {
      this.buildBoard(id);
      this.buildWorld(coords);
      return this.loopForever();
    }
  };

  global = typeof exports !== "undefined" && exports !== null ? exports : this;

  global.LifeUI = LifeUI;

}).call(this);

/*
//@ sourceMappingURL=lifeui.map
*/
